// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrismBot;
using PrismBot.SDK;
using PrismBot.SDK.Data;

#nullable disable

namespace PrismBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20230121133009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("PrismBot.Player", b =>
                {
                    b.Property<long>("QQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QQ");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
