// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrismBot;
using PrismBot.SDK;
using PrismBot.SDK.Data;

#nullable disable

namespace PrismBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20230121141433_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("PrismBot.Group", b =>
                {
                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentGroupName")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupName");

                    b.HasIndex("ParentGroupName");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PrismBot.Permission", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlayerQQ")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionName");

                    b.HasIndex("GroupName");

                    b.HasIndex("PlayerQQ");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("PrismBot.Player", b =>
                {
                    b.Property<long>("QQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QQ");

                    b.HasIndex("GroupName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PrismBot.Group", b =>
                {
                    b.HasOne("PrismBot.Group", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentGroupName");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PrismBot.Permission", b =>
                {
                    b.HasOne("PrismBot.Group", null)
                        .WithMany("Permissions")
                        .HasForeignKey("GroupName");

                    b.HasOne("PrismBot.Player", null)
                        .WithMany("Permissions")
                        .HasForeignKey("PlayerQQ");
                });

            modelBuilder.Entity("PrismBot.Player", b =>
                {
                    b.HasOne("PrismBot.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupName");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PrismBot.Group", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("PrismBot.Player", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
